version: '3'
services:

    nfs:
        image: itsthenetwork/nfs-server-alpine
        container_name: nfs-server
        restart: unless-stopped
        privileged: true
        environment: 
            - SHARED_DIRECTORY=/data
        volumes:
            - ./nfs-storage:/data

        ports:
            - "2049:2049"
