version: '3'
services:

  influxdb:
    image: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 25826:25826/udp
    networks:
      - grafana-net
    volumes:
      - influxdb:/var/lib/influxdb


  grafana:
    image: grafana
    networks:
      - grafana-net
    ports:
      - 3000:3000

networks:
  grafana-net:

volumes:
  influxdb: